/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Sort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void mergeSort() {
        int[]  emptyArr = {};
        assertEquals(emptyArr, App.mergeSort(emptyArr));

        // regular array
        int[]  regularArr = {8,4,23,42,16,15};
        assertEquals("[4, 8, 15, 16, 23, 42]", Arrays.toString(App.mergeSort(regularArr)));

    }

}
