/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void EmptyGraphTest(){
        Graph graph = new Graph();
        assertEquals(null, graph.toString());
        assertEquals(0, graph.size());
    }


    @Test
    void GraphAdd(){
        Graph graph = new Graph();
        graph.addNode("1");
        graph.addNode("2");
        graph.addNode("3");
        assertEquals("[Graph{label='1', weight=0}, Graph{label='2', weight=0}, Graph{label='3', weight=0}]", graph.getNodes().toString());
        assertEquals(3, graph.size());
    }

    @Test void GraphAddEdge(){

        Graph graph = new Graph();
        graph.addNode("1");
        graph.addNode("2");
        graph.addNode("3");

        graph.addEdge("1", "2");
        graph.addEdge("2", "3");
        graph.addEdge("3", "1");
        assertEquals("[Graph{label='1', weight=0}, Graph{label='2', weight=0}, Graph{label='3', weight=0}]",graph.getNodes().toString());
        assertEquals(3, graph.size());


    }

}
