/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Insertion.Sort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void insertionSort() {
        // empty
        int[]  empty = {};
        assertEquals("", App.InsertionSort(empty));


        int[]  regularArr = {8,4,23,42,16,15};
        assertEquals("[4, 8, 15, 16, 23, 42]", Arrays.toString(App.InsertionSort(regularArr)));

    }
}
